VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use the same SSH key for each VM.
  config.ssh.insert_key = false
  config.vm.box = "centos/8"

  # This message will run when all other completed.
  config.vm.post_up_message = "Test environment for vagrant servers."

  # Adapter 2: Use private network Host-Only with fixed IP in same subnet.
  # Netmask 192.168.18.0/24
  # Host can access them.
  # They can access each other, host and Internet.

  # This is default folder mapping.
  # config.vm.synced_folder "./Temp", "/vagrant", owner: "root", group: "root"

  # To prevent auto upgrading  kernel-devel. That will cause following:
  # Error: Unable to find a match: kernel-devel-4.18.0-240.1.1.el8_3.x86_64
  config.vbguest.auto_update = false

  # Install software.
  config.vm.provision "shell", path: "Scripts/Prepare_OS.sh"
  config.vm.provision "shell", path: "Scripts/Prepare_System.sh"

  # Global config.
  # Enable password login.
  config.vm.provision "shell", inline: <<-END
    # Testing: sudo sed "/^PasswordAuthentication.*$/d; /^#PasswordAuthentication.*$/a PasswordAuthentication yes" /etc/ssh/sshd_config
    sudo sed -i "/^PasswordAuthentication.*$/d" /etc/ssh/sshd_config
    sudo sed -i "/^#PasswordAuthentication.*$/a PasswordAuthentication yes" /etc/ssh/sshd_config
    sudo systemctl restart sshd
  END


  config.vm.define "vagrantDbServer" do |vagrantDbServer|
    vagrantDbServer.vm.provider "virtualbox" do |vb|
      vb.name = "Vagrant_vagrantDbServer"
      # Default is 1024M.
      vb.memory = 2048
      # Default is 1 CPU.
      vb.cpus = 2
    end

    vagrantDbServer.vm.hostname = "db.djsilenceboy.com"
    vagrantDbServer.vm.network "private_network", ip: "192.168.18.61"

    # Local provision will run after global provision.
    vagrantDbServer.vm.provision "shell", path: "Scripts/Install_PostgreSQL.sh"
    # It requires to config after VM created.
    vagrantDbServer.vm.provision "shell", path: "Scripts/Install_MySQL.sh"
    vagrantDbServer.vm.provision "shell", path: "Scripts/Install_MongoDB.sh"
    # It is not easy to install for Vagrant.
    # vagrantDbServer.vm.provision "shell", path: "Scripts/Install_OracleXE.sh"

    # vagrantDbServer.disksize.size = "20GB"
  end


  config.vm.define "vagrantApplicationServer" do |vagrantApplicationServer|
    vagrantApplicationServer.vm.provider "virtualbox" do |vb|
      vb.name = "Vagrant_vagrantApplicationServer"
      # Default is 1024M.
      vb.memory = 3072
      # Default is 1 CPU.
      vb.cpus = 2
    end

    vagrantApplicationServer.vm.hostname = "appsvr.djsilenceboy.com"
    vagrantApplicationServer.vm.network "private_network", ip: "192.168.18.62"

    # Local provision will run after global provision.
    vagrantApplicationServer.vm.provision "shell", path: "Scripts/Prepare_Development.sh"
    vagrantApplicationServer.vm.provision "shell", path: "Scripts/Install_Ansible.sh"
    vagrantApplicationServer.vm.provision "shell", path: "Scripts/Install_httpd.sh"
    vagrantApplicationServer.vm.provision "shell", path: "Scripts/Install_Tomcat.sh"
    vagrantApplicationServer.vm.provision "shell", path: "Scripts/Install_Jenkins.sh"

    # vagrantApplicationServer.disksize.size = "20GB"
  end


  config.vm.define "vagrantJbossServer" do |vagrantJbossServer|
    vagrantJbossServer.vm.provider "virtualbox" do |vb|
      vb.name = "Vagrant_vagrantJbossServer"
      # Default is 1024M.
      vb.memory = 3072
      # Default is 1 CPU.
      vb.cpus = 2
    end

    vagrantJbossServer.vm.hostname = "jboss.djsilenceboy.com"
    vagrantJbossServer.vm.network "private_network", ip: "192.168.18.63"

    # Local provision will run after global provision.
    vagrantJbossServer.vm.provision "shell", path: "Scripts/Prepare_Development.sh"
    # vagrantJbossServer.vm.provision "shell", path: "Scripts/Install_JBossEAP.sh"
  end
end
