//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.08 at 05:01:37 PM GMT+08:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://singtel.com/schema/example_test/local", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.djs.test.wsclient.example_test;
