---
- name: Install httpd
  hosts: all
  become: True
  tasks:
    - name: Install application
      dnf:
        name: httpd
        state: latest

    - name: Config service
      shell: sed -i "s/\(ServerName\).*$/\1  "$(hostname)"/g" /etc/httpd/conf/httpd.conf

    - name: Enable and start service
      service:
        name: httpd
        enabled: yes
        state: started
