---
- name: Install PostgreSQL v9.6
  hosts: all
  become: True
  tasks:
    - name: Install repo
      dnf:
        name: http://yum.postgresql.org/9.6/redhat/rhel-latest-x86_64/pgdg-redhat-repo-latest.noarch.rpm

    - name: Install DB 1
      dnf:
        name: postgresql96
        state: latest

    - name: Install DB 2
      dnf:
        name: postgresql96-server
        state: latest

    - name: Install DB 3
      dnf:
        name: postgresql96-contrib
        state: latest

    - name: Initial DB
      shell: /usr/pgsql-9.6/bin/postgresql96-setup initdb

    - name: Enable remote access 1
      shell: sed -i '/.*listen_addresses.*/ a\listen_addresses = '"'"'*'"'" /var/lib/pgsql/9.6/data/postgresql.conf

    - name: Enable remote access 2
      shell: sed -i 's/^local.*$/local   all             all                                     trust/g' /var/lib/pgsql/9.6/data/pg_hba.conf

    - name: Enable remote access 3
      shell: sed -i '$ a\host    all             all             192.168.0.1/16          md5' /var/lib/pgsql/9.6/data/pg_hba.conf

    - name: Enable and start service
      service:
        name: postgresql-9.6
        enabled: yes
        state: started

    - name: Sleep
      pause:
        seconds: 5

    - name: Create role
      shell: psql -c "CREATE ROLE tester WITH LOGIN CREATEDB PASSWORD 'P@ssw0rd'"
      become: true
      become_user: postgres

    - name: Create DB
      shell: psql -c "CREATE DATABASE test OWNER tester"
      become: true
      become_user: postgres

    - name: Grant privileges
      shell: psql -c "GRANT ALL PRIVILEGES ON DATABASE test TO tester"
      become: true
      become_user: postgres
