---
- name: Install desktop
  hosts: all
  become: True
  tasks:
    - name: Install desktop group
      dnf:
        name: "@^Server with GUI"
        state: present

    - name: Install tools
      dnf:
        name: "{{ item }}"
        state: latest
      with_items:
        - tigervnc-server
        - xrdp

    - name: Change default runlevel to graphical
      shell: systemctl set-default graphical.target

    - name: Setup VNC server 1
      shell: cp /usr/lib/systemd/system/vncserver@.service /etc/systemd/system/vncserver@.service

    - name: Setup VNC server 2
      shell: sed -i "s/<USER>/vagrant/g" /etc/systemd/system/vncserver@.service

    - name: Setup VNC server 3
      file:
        path: /home/vagrant/.vnc
        state: directory
        owner: vagrant
        group: vagrant
        mode: 0700

    - name: Setup VNC server 4
      shell: echo "P@ssw0rd" | vncpasswd -f > /home/vagrant/.vnc/passwd

    - name: Setup VNC server 5
      file:
        path: /home/vagrant/.vnc/passwd
        owner: vagrant
        group: vagrant
        mode: 0600

    - name: VNC service
      systemd:
        name: vncserver@:1
        daemon_reload: yes
        enabled: true
        state: started

    - name: XRDP service
      service:
        name: xrdp
        enabled: yes
        state: started

    - name: Setup XRDP 1
      shell: chcon --type=bin_t /usr/sbin/xrdp

    - name: Setup XRDP 2
      shell: chcon --type=bin_t /usr/sbin/xrdp-sesman
