---
- name: Install JBoss Wildfly
  hosts: all
  become: True
  tasks:
    - name: Pull image
      docker_image:
        name: jboss/wildfly

    - name: Create container
      docker_container:
        name: wildfly
        image: jboss/wildfly
        state: started
        published_ports:
          - "8100:8080"
          - "9990:9990"
        volumes:
          - /opt/jboss/wildfly/standalone/deployments:/opt/jboss/wildfly/standalone/deployments
        command: /opt/jboss/wildfly/bin/standalone.sh -bmanagement 0.0.0.0
        restart_policy: always
