---
- name: Install Tomcat v9.0
  hosts: all
  become: True
  tasks:
    - name: Pull image
      docker_image:
        name: tomcat:9

    - name: Create container
      docker_container:
        name: tomcat
        image: tomcat:9
        state: started
        env:
          JPDA_ADDRESS: 8000
          JPDA_TRANSPORT: dt_socket
        published_ports:
          - "8080:8080"
          - "8082:8000"
        volumes:
          - /opt/tomcat/webapps:/opt/tomcat/webapps
