---
- name: Install Nginx
  hosts: all
  become: True
  tasks:
    - name: Pull image
      docker_image:
        name: nginx

    - name: Create container
      docker_container:
        name: webfrontend
        image: nginx
        state: started
        published_ports:
          - "8070:80"
        restart_policy: always
