---
- name: Install Docker
  hosts: all
  become: True
  tasks:
    - name: Setup repo
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker CE
      dnf:
        name: "{{ item }}"
        state: latest
      with_items:
        - docker-ce
        - docker-ce-cli

    - name: Enable and start service
      service:
        name: docker
        enabled: yes
        state: started

    - name: Sleep
      pause:
        seconds: 5

    - name: Download Docker Compose
      shell: curl -L -o /usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/1.28.2/docker-compose-`uname -s`-`uname -m`

    - name: Change mode of file
      shell: chmod +x /usr/local/bin/docker-compose

    - name: Add Docker Compose path to sudo
      shell: sed -i "s/^Defaults.*:\/usr\/bin$/&:\/usr\/local\/bin/g" /etc/sudoers

    - name: Install Python module docker-py
      shell: pip install docker-py
