---
- name: Install Tomcat v9.0
  hosts: all
  become: True
  vars:
    remote_temp_path: /tmp
    tomcat_installation_parentfolder: /opt
    tomcat_installation_folder: tomcat
  tasks:
    - name: Pull image
      docker_image:
        name: tomcat:9

    - name: Create container
      docker_container:
        name: tomcat
        image: tomcat:9
        state: started
        published_ports:
          - "8080:8080"
          - "8089:8009"
        restart_policy: always

    - name: Add admin user
      shell: docker exec -t tomcat bash -c 'sed -i '"'"'/<\/tomcat-users>/ i\  <user username="admin" password="P@ssw0rd" roles="manager-gui,manager-status,manager-script"/>'"'"' /usr/local/tomcat/conf/tomcat-users.xml'

    - name: Enable default apps
      shell: docker exec -t tomcat bash -c 'mv /usr/local/tomcat/webapps.dist/* /usr/local/tomcat/webapps/'

    - name: Enable remote access console (from 192.168.0.0/16)
      shell: docker exec -t tomcat bash -c 'sed -i '"'"'s/\(^.*0:1\)\(.*$\)/\1|192\\.168\\.\\d+\\.\\d+\2/g'"'"' /usr/local/tomcat/webapps/manager/META-INF/context.xml'

    - name: Restart container
      docker_container:
        name: tomcat
        image: tomcat:9
        state: started
        restart: yes
