---
- name: Install development tools
  hosts: all
  become: True
  tasks:
    - name: Install development group
      dnf:
        name: "@Development tools"
        state: present

    - name: Install tools
      dnf:
        name: "{{ item }}"
        state: latest
      with_items:
        - python36-devel
        - openssl-devel
