---
- name: Setup CentOS environment
  hosts: all
  become: True
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Install tools
      dnf:
        name: "{{ item }}"
        state: latest
      with_items:
        # - bind-utils
        # - cifs-utils
        # - git
        # - net-tools
        - nmap
        - openssl
        - openssl-devel
        - perl
        # - python3
        - tcpdump
        # - traceroute
        # - unzip
        # - whois
        # - yum-utils
        # - zip
        - java-1.8.0-openjdk
        - java-1.8.0-openjdk-devel

#    - name: Upgrade pip
#      shell: python3 -m pip install --upgrade pip

    - name: Disable and stop firewall services
      service:
        name: "{{ item }}"
        enabled: no
        state: stopped
      ignore_errors: yes
      with_items:
        - firewalld
        # - iptables
        # - ipset

    - name: Limit kept kernels
      shell: sed -i "s/\(installonly_limit=\).*$/\12/g" /etc/yum.conf
