//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.08 at 05:01:37 PM GMT+08:00 
//


package com.djs.learn.wsclient.wap_push;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sendWapPushResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sendWapPushResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="wapPushResponse" type="{http://www.csapi.org/schema/parlayx/djs/sample/ext/wappush/v1_0}WapPushRespData"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sendWapPushResponse", propOrder = {
    "wapPushResponse"
})
@XmlRootElement(name = "sendWapPushResponse")
public class SendWapPushResponse {

    @XmlElement(namespace = "http://www.csapi.org/schema/parlayx/djs/sample/ext/wappush/v1_0/local", required = true)
    protected WapPushRespData wapPushResponse;

    /**
     * Gets the value of the wapPushResponse property.
     * 
     * @return
     *     possible object is
     *     {@link WapPushRespData }
     *     
     */
    public WapPushRespData getWapPushResponse() {
        return wapPushResponse;
    }

    /**
     * Sets the value of the wapPushResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link WapPushRespData }
     *     
     */
    public void setWapPushResponse(WapPushRespData value) {
        this.wapPushResponse = value;
    }

}
