# Purpose:
#   Common: Execute remote script and save info to local temp file.
#
# Usage:
#   Used by main playbook as module.
#
# Update log: (date / version / author : comments)
# 2017-04-14 / 1.0.0 / Du Jiang : Creation
# 2017-04-17 / 1.1.0 / Du Jiang : Add one line header, and succeeded/failed
# 2017-04-21 / 1.2.0 / Du Jiang : Use subfolder for temp and output files
# 2017-04-23 / 1.3.0 / Du Jiang : Pass inventory_hostname to remote script; add remote_extra_parameters (a list of parameters separated by comma)
---
- name: Execute remote script and save info to local temp file
  # Each endpoint has a separated file.
  hosts: all
  gather_facts: False
  tasks:
    - name: Test remote host and port
      local_action: shell echo > /dev/tcp/"{{ansible_ssh_host}}"/"{{ansible_ssh_port}}"
      become: False
      ignore_errors: True
      register: echo_result_info

    - debug: var=echo_result_info

    - name: Capture remote output
      script: "{{local_script_folder}}/{{remote_script}} {{inventory_hostname}} {{remote_extra_parameters}}"
      become: True
      when: echo_result_info|succeeded
      ignore_errors: True
      register: remote_result_info

    - debug: var=remote_result_info


    - name: Save output to local temp file (succeeded)
      # This can append contents to the file.
      local_action: lineinfile line="{{remote_result_info.stdout}}" dest="{{local_temp_file}}" create=Yes
      become: False
      when: echo_result_info|succeeded and remote_result_info|succeeded


    - name: Save output to local temp file (echo failed, multiple lines)
      # This can append contents to the file.
      local_action: lineinfile line="Host ID{{":"}} {{inventory_hostname}}\nError message{{":"}}\n{{echo_result_info.stderr}}\n----------------------------------------" dest="{{local_temp_file_failed}}" create=Yes
      become: False
      when: echo_result_info|failed and multiple_lines

    - name: Save output to local temp file (remote failed, multiple lines)
      # This can append contents to the file.
      local_action: lineinfile line="Host ID{{":"}} {{inventory_hostname}}\nError message{{":"}}\n{{remote_result_info.msg|default(remote_result_info.stderr)}}\n----------------------------------------" dest="{{local_temp_file_failed}}" create=Yes
      become: False
      when: remote_result_info|failed and multiple_lines


    - name: Save output to local temp file (echo failed, one line)
      # This can append contents to the file.
      local_action: lineinfile line="{{inventory_hostname}}, {{echo_result_info.stderr|regex_replace('\n', '; ')}}" dest="{{local_temp_file_failed}}" create=Yes
      become: False
      when: echo_result_info|failed and (not multiple_lines)

    - name: Save output to local temp file (remote failed, one line)
      # This can append contents to the file.
      local_action: lineinfile line="{{inventory_hostname}}, {{remote_result_info.msg|default(remote_result_info.stderr)|regex_replace('\n', '; ')}}" dest="{{local_temp_file_failed}}" create=Yes
      become: False
      when: remote_result_info|failed and (not multiple_lines)
