# Purpose:
#   Common: Combine local temp files into one local output file.
#
# Usage:
#   Used by main playbook as module.
#
# Update log: (date / version / author : comments)
# 2017-04-21 / 1.0.0 / Du Jiang : Creation
# 2017-05-26 / 1.1.0 / Du Jiang : Not gather_facts
---
- name: Combine local temp files into one output file
  hosts: all
  connection: local
  gather_facts: False
  become: False
  tasks:
    - name: Combine local temp file to one output file (succeeded)
      # This can append contents to the file.
      local_action: shell find "{{local_temp_subfolder}}" -name "*{{local_output_file_postfix}}" ! -name "*{{failed_infix}}{{local_output_file_postfix}}" -exec bash -c "cat {} >> {{local_output_file}}" \;
      run_once: True

    - name: Combine local temp file to one output file (failed)
      # This can append contents to the file.
      local_action: shell find "{{local_temp_subfolder}}" -name "*{{failed_infix}}{{local_output_file_postfix}}" -exec bash -c "cat {} >> {{local_output_file}}" \;
      run_once: True
