SELECT *
FROM PLAN_TABLE;

SELECT cardinality "Rows",
       lpad(' ',level-1)||operation||' '|| options||' '||object_name "Plan"
FROM PLAN_TABLE
CONNECT BY prior id = parent_id
        AND prior statement_id = statement_id
START WITH id = 0
      AND statement_id = 'test'
ORDER BY id;

EXPLAIN PLAN SET STATEMENT_ID = 'test' FOR
SELECT a.EMPLOYEE_ID, a.MANAGER_ID, a.FIRST_NAME || ' ' || a.LAST_NAME
FROM EMPLOYEES a
WHERE EXISTS
      (SELECT 1
       FROM EMPLOYEES b
       WHERE (b.MANAGER_ID = a.EMPLOYEE_ID))
ORDER BY a.EMPLOYEE_ID;

SELECT a.EMPLOYEE_ID, a.MANAGER_ID, a.FIRST_NAME || ' ' || a.LAST_NAME
FROM EMPLOYEES a
WHERE NOT EXISTS
      (SELECT 1
       FROM EMPLOYEES b
       WHERE (b.MANAGER_ID = a.EMPLOYEE_ID))
ORDER BY a.EMPLOYEE_ID;

SELECT a.EMPLOYEE_ID, a.MANAGER_ID, a.FIRST_NAME || ' ' || a.LAST_NAME, COUNT(*)
FROM EMPLOYEES a, EMPLOYEES b
WHERE (b.MANAGER_ID = a.EMPLOYEE_ID)
GROUP BY a.EMPLOYEE_ID, a.MANAGER_ID, a.FIRST_NAME || ' ' || a.LAST_NAME
ORDER BY a.EMPLOYEE_ID;

SELECT a.EMPLOYEE_ID, a.MANAGER_ID, a.FIRST_NAME || ' ' || a.LAST_NAME, b.EMPLOYEE_ID, b.FIRST_NAME || ' ' || b.LAST_NAME
FROM EMPLOYEES a, EMPLOYEES b
WHERE (b.MANAGER_ID = a.EMPLOYEE_ID)
ORDER BY a.EMPLOYEE_ID, b.EMPLOYEE_ID;


SELECT JOB_ID, SALARY, COUNT(*)
FROM EMPLOYEES
GROUP BY JOB_ID, SALARY
ORDER BY 1, 2;

SELECT COUNT(*), COUNT(MANAGER_ID), COUNT(DISTINCT MANAGER_ID)
FROM EMPLOYEES;

SELECT DISTINCT MANAGER_ID
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE EMPLOYEE_ID <= 110;

SELECT EMPLOYEE_ID, FIRST_NAME, LTRIM(FIRST_NAME, 'iDa'), RTRIM(FIRST_NAME, 'cre'), REPLACE(FIRST_NAME, 'a', '*'), TRANSLATE(FIRST_NAME, 'ae', '*#')
FROM EMPLOYEES
WHERE EMPLOYEE_ID <= 110;

SELECT EMPLOYEE_ID, FIRST_NAME, LPAD(FIRST_NAME, 20, '+'), RPAD(FIRST_NAME, 20, '+')
FROM EMPLOYEES
WHERE EMPLOYEE_ID <= 110;

SELECT JOB_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY JOB_ID
UNION
SELECT COUNTRY_ID, COUNT(*)
FROM LOCATIONS
GROUP BY COUNTRY_ID;

SELECT JOB_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY JOB_ID
UNION
SELECT COUNTRY_ID, LOCATION_ID
FROM LOCATIONS;
