VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use the same SSH key for each VM.
  config.ssh.insert_key = false
  config.vm.box = "ubuntu/xenial64"

  # This message will run when all other completed.
  config.vm.post_up_message = "Test environment for Ansible servers."

  # Adapter 2: Use private network Host-Only with fixed IP in same subnet.
  # Netmask 192.168.10.0/24
  # Host can access them.
  # They can access each other, host and Internet.

  # This is default folder mapping.
  # config.vm.synced_folder "./Temp", "/vagrant", owner: "root", group: "root"

  # Global config.
  # Install package for ifconfig.
  config.vm.provision "shell", inline: "sudo apt install -y net-tools"
  # Enable password login.
  config.vm.provision "shell", inline: <<-END
    # Testing: sudo sed "/^PasswordAuthentication.*$/d; /^#PasswordAuthentication.*$/a PasswordAuthentication yes" /etc/ssh/sshd_config
    sudo sed -i "/^PasswordAuthentication.*$/d" /etc/ssh/sshd_config
    sudo sed -i "/^#PasswordAuthentication.*$/a PasswordAuthentication yes" /etc/ssh/sshd_config
    sudo service ssh restart
  END

  # Default is 10G.
  config.disksize.size = "50GB"

  config.vm.define "ansibleUbuntu" do |ansibleUbuntu|
    ansibleUbuntu.vm.provider "virtualbox" do |vb|
      vb.name = "Vagrant_ansibleUbuntu"
      # Default is 1024M.
      vb.memory = 4096
      # Default is 1 CPU.
      vb.cpus = 2
      vb.gui = true
    end

    ansibleUbuntu.vm.hostname = "ubuntu.djsilenceboy.com"
    ansibleUbuntu.vm.network "private_network", ip: "192.168.10.71"

    # Local provision will run after global provision.
    # Re-configure DNS.
    ansibleUbuntu.vm.provision "shell", run: "always", inline: "resolvconf -u"
  end
end
