VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use the same SSH key for each VM.
  config.ssh.insert_key = false
  config.vm.box = "centos/7"

  # This message will run when all other completed.
  config.vm.post_up_message = "This is vagrant test sample."

  # Adapter 1: Use default network NAT with DHCP.
  # Netmask 10.0.2.0/24; Always assign IP address 10.0.2.15
  # Host cannot access them.
  # They cannot access each other and Internet.
  # They can access host.

  # Global config.
  # Enable password login.
  config.vm.provision "shell", inline: <<-END
    # Testing: sudo sed "/^PasswordAuthentication.*$/d; /^#PasswordAuthentication.*$/a PasswordAuthentication yes" /etc/ssh/sshd_config
    sudo sed -i "/^PasswordAuthentication.*$/d" /etc/ssh/sshd_config
    sudo sed -i "/^#PasswordAuthentication.*$/a PasswordAuthentication yes" /etc/ssh/sshd_config
    sudo systemctl restart sshd
  END


  config.vm.define "vagrantep5" do |vagrantep5|
    vagrantep5.vm.provider "virtualbox" do |vb|
      vb.name = "Vagrant_vagrantep5"
    end
    vagrantep5.vm.hostname = "vagrantep5.djsilenceboy.com"
    # Forward port Guest 80 -> Host localhost:9080.
    vagrantep5.vm.network "forwarded_port", guest: 80, host: 9080
    # Forward port Guest 80 -> Host localhost:9443.
    vagrantep5.vm.network "forwarded_port", guest: 443, host: 9443
    # Default host to guest SSH port localhost:2222.
  end


  config.vm.define "vagrantep6" do |vagrantep6|
    vagrantep6.vm.provider "virtualbox" do |vb|
      vb.name = "Vagrant_vagrantep6"
    end
    vagrantep6.vm.hostname = "vagrantep6.djsilenceboy.com"
    # Forward port Guest 80 -> Host localhost:9081.
    vagrantep6.vm.network "forwarded_port", guest: 80, host: 9081
    # Forward port Guest 80 -> Host localhost:9444.
    vagrantep6.vm.network "forwarded_port", guest: 443, host: 9444
    # Default host to guest SSH port localhost:2200.
  end
end
