---
- name: Install PostgreSQL v9.5
  hosts: VagrantDbServer
  become: True
  tasks:
    - name: Install repo
      yum:
        name: http://yum.postgresql.org/9.5/redhat/rhel-7-x86_64/pgdg-centos95-9.5-3.noarch.rpm

    - name: Install DB 1
      yum:
        name: postgresql95-server
        state: latest
        update_cache: yes

    - name: Install DB 2
      yum:
        name: postgresql95-contrib
        state: latest
        update_cache: yes

    - name: Initial DB
      shell: /usr/pgsql-9.5/bin/postgresql95-setup initdb

    - name: Enable remote access 1
      shell: sed -i '/.*listen_addresses.*/ a\listen_addresses = '"'"'*'"'" /var/lib/pgsql/9.5/data/postgresql.conf

    - name: Enable remote access 2
      shell: sed -i 's/^local.*$/local   all             all                                     trust/g' /var/lib/pgsql/9.5/data/pg_hba.conf

    - name: Enable remote access 3
      shell: sed -i '$ a\host    all             all             192.168.0.1/24          md5' /var/lib/pgsql/9.5/data/pg_hba.conf

    - name: Enable and start service
      service:
        name: postgresql-9.5
        enabled: yes
        state: started

    - name: Sleep
      pause:
        seconds: 5

    - name: Create role
      shell: psql -c "CREATE ROLE tester WITH LOGIN CREATEDB PASSWORD 'P@ssw0rd'"
      become: true
      become_user: postgres

    - name: Create DB
      shell: psql -c "CREATE DATABASE test OWNER tester"
      become: true
      become_user: postgres

    - name: Grant privileges
      shell: psql -c "GRANT ALL PRIVILEGES ON DATABASE test TO tester"
      become: true
      become_user: postgres
