---
- include: VagrantDockerServer.yml
- include: Playbooks/Install_Docker_Nginx.yml
- include: Playbooks/Install_Docker_Tomcat.yml
- include: Playbooks/Install_Docker_Jenkins.yml
- include: Playbooks/Install_Docker_JBoss.yml
