---
- include: Playbooks/Setup_CentOS.yml
- include: Playbooks/Install_Development.yml
- include: Playbooks/Install_Ansible.yml
- include: Playbooks/Install_httpd.yml
- include: Playbooks/Install_Tomcat.yml
- include: Playbooks/Install_Tomcat_Jenkins.yml
