---
- name: Install MySQL v5.7
  hosts: VagrantDbServer
  become: True
  vars:
    local_config_file_path: files
    remote_temp_path: /tmp
  tasks:
    - name: Install repo
      yum:
        name: https://repo.mysql.com/yum/mysql-5.7-community/el/7/x86_64/mysql57-community-release-el7-10.noarch.rpm

    - name: Install DB
      yum:
        name: mysql-community-server
        state: latest
        update_cache: yes

    - name: Enable and start service
      service:
        name: mysqld
        enabled: yes
        state: started

    - name: Sleep
      pause:
        seconds: 5

    - name: Copy config files to remote
      copy:
        src: "{{ item }}"
        dest: "{{ remote_temp_path }}/"
        mode: "a+x"
      with_fileglob:
        - "{{ local_config_file_path }}/MySQL_Config_*.sh"

    - debug: msg="Please run {{ remote_temp_path }}/MySQL_Config_1.sh and then {{ remote_temp_path }}/MySQL_Config_2.sh."
