
package com.djs.learn.wsclient.example_test;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Jan 30 17:41:27 GMT+08:00 2012
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "ServiceException", targetNamespace = "http://www.csapi.org/schema/parlayx/common/v2_1")
public class ServiceException extends Exception {
    public static final long serialVersionUID = 20120130174127L;
    
    private org.csapi.schema.parlayx.common.v2_1.ServiceException serviceException;

    public ServiceException() {
        super();
    }
    
    public ServiceException(String message) {
        super(message);
    }
    
    public ServiceException(String message, Throwable cause) {
        super(message, cause);
    }

    public ServiceException(String message, org.csapi.schema.parlayx.common.v2_1.ServiceException serviceException) {
        super(message);
        this.serviceException = serviceException;
    }

    public ServiceException(String message, org.csapi.schema.parlayx.common.v2_1.ServiceException serviceException, Throwable cause) {
        super(message, cause);
        this.serviceException = serviceException;
    }

    public org.csapi.schema.parlayx.common.v2_1.ServiceException getFaultInfo() {
        return this.serviceException;
    }
}
