
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.djs.learn.myfirstservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-08-26T23:17:24.517+08:00
 * Generated source version: 2.7.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "MyFirstService",
                      portName = "MyFirstService2SOAP",
                      targetNamespace = "http://www.example.org/MyServices/",
                      wsdlLocation = "http://www.example.org/MySecondService?wsdl",
                      endpointInterface = "com.djs.myfirstservice.MyFirstService2")
                      
public class MyFirstService2Impl implements MyFirstService2 {

    private static final Logger LOG = Logger.getLogger(MyFirstService2Impl.class.getName());

    /* (non-Javadoc)
     * @see com.djs.myfirstservice.MyFirstService2#newOperation(com.djs.myfirstservice.NewOperation2  parameters ,)com.djs.myfirstservice.NewOperation2  parameters2 )*
     */
    public com.djs.learn.myfirstservice.NewOperationResponse2 newOperation(NewOperation2 parameters,NewOperation2 parameters2) { 
        LOG.info("Executing operation newOperation");
        System.out.println(parameters);
        System.out.println(parameters2);
        try {
            com.djs.learn.myfirstservice.NewOperationResponse2 _return = new com.djs.learn.myfirstservice.NewOperationResponse2();
            _return.setOut("Out-1137701491");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
