
package com.bea.wsdl.wlcp.wlng.session_manager.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "fault", targetNamespace = "http://www.bea.com/wsdl/wlcp/wlng/session_manager/service")
public class GeneralException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private GeneralException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public GeneralException_Exception(String message, GeneralException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public GeneralException_Exception(String message, GeneralException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.bea.wsdl.wlcp.wlng.session_manager.service.GeneralException
     */
    public GeneralException getFaultInfo() {
        return faultInfo;
    }

}
