//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.08 at 05:13:14 PM GMT+08:00 
//


package com.bea.wsdl.wlcp.wlng.session_manager.service;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bea.wsdl.wlcp.wlng.session_manager.service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bea.wsdl.wlcp.wlng.session_manager.service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetSessionResponse }
     * 
     */
    public GetSessionResponse createGetSessionResponse() {
        return new GetSessionResponse();
    }

    /**
     * Create an instance of {@link GetSessionRemainingLifeTimeResponse }
     * 
     */
    public GetSessionRemainingLifeTimeResponse createGetSessionRemainingLifeTimeResponse() {
        return new GetSessionRemainingLifeTimeResponse();
    }

    /**
     * Create an instance of {@link ChangeApplicationPasswordResponse }
     * 
     */
    public ChangeApplicationPasswordResponse createChangeApplicationPasswordResponse() {
        return new ChangeApplicationPasswordResponse();
    }

    /**
     * Create an instance of {@link DestroySessionResponse }
     * 
     */
    public DestroySessionResponse createDestroySessionResponse() {
        return new DestroySessionResponse();
    }

    /**
     * Create an instance of {@link RefreshSessionResponse }
     * 
     */
    public RefreshSessionResponse createRefreshSessionResponse() {
        return new RefreshSessionResponse();
    }

    /**
     * Create an instance of {@link DestroySession }
     * 
     */
    public DestroySession createDestroySession() {
        return new DestroySession();
    }

    /**
     * Create an instance of {@link GetSessionRemainingLifeTime }
     * 
     */
    public GetSessionRemainingLifeTime createGetSessionRemainingLifeTime() {
        return new GetSessionRemainingLifeTime();
    }

    /**
     * Create an instance of {@link RefreshSession }
     * 
     */
    public RefreshSession createRefreshSession() {
        return new RefreshSession();
    }

    /**
     * Create an instance of {@link Fault }
     * 
     */
    public Fault createFault() {
        return new Fault();
    }

    /**
     * Create an instance of {@link GetSession }
     * 
     */
    public GetSession createGetSession() {
        return new GetSession();
    }

    /**
     * Create an instance of {@link ChangeApplicationPassword }
     * 
     */
    public ChangeApplicationPassword createChangeApplicationPassword() {
        return new ChangeApplicationPassword();
    }

}
