CREATE TABLE PSS_GAME_LIST (
  NAME                        VARCHAR(100) NOT NULL,
  SUB_NAME                    VARCHAR(50),
  PROVIDER                    VARCHAR(50),
  GENRES                      VARCHAR(50),
  PLATFORMS                   VARCHAR(30) NOT NULL,
  RELEASE_DATE                TIMESTAMP,
  DISPLAY_PRICE               VARCHAR(12) NOT NULL,
  PRICE_VALUE                 INT NOT NULL,
  DISCOUNT_PERCENT            INT NOT NULL,
  DISCOUNT_FROM               TIMESTAMP,
  DISCOUNT_TO                 TIMESTAMP,
  CONTENT_TYPE                VARCHAR(12),
  SKU_ID                      VARCHAR(50) NOT NULL,
  GAME_POST                   VARCHAR(100)
);

CREATE INDEX PSS_GAME_LIST_1 ON PSS_GAME_LIST (NAME);
CREATE INDEX PSS_GAME_LIST_2 ON PSS_GAME_LIST (PLATFORMS, NAME);
CREATE INDEX PSS_GAME_LIST_3 ON PSS_GAME_LIST (PLATFORMS, DISCOUNT_PERCENT, PRICE_VALUE);
