
package com.singtel.ndp.ext.example_test.v1_0.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.singtel.schema.example_test.local.SendDataRequest;
import com.singtel.schema.example_test.local.SendDataResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SendDataPort", targetNamespace = "http://singtel.com/ndp/ext/example_test/v1_0/interface")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.singtel.schema.example_test.local.ObjectFactory.class,
    org.csapi.schema.parlayx.common.v2_1.ObjectFactory.class
})
public interface SendDataPort {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.singtel.schema.example_test.local.SendDataResponse
     * @throws ServiceException
     * @throws PolicyException
     */
    @WebMethod
    @WebResult(name = "sendDataResponse", targetNamespace = "http://singtel.com/schema/example_test/local", partName = "result")
    public SendDataResponse sendData(
        @WebParam(name = "sendDataRequest", targetNamespace = "http://singtel.com/schema/example_test/local", partName = "parameters")
        SendDataRequest parameters)
        throws PolicyException, ServiceException
    ;

}
