
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.djs.myfirstservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-08-26T23:17:24.532+08:00
 * Generated source version: 2.7.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "MyFirstService",
                      portName = "MyFirstServiceSOAP",
                      targetNamespace = "http://www.example.org/MyServices/",
                      wsdlLocation = "http://www.example.org/MySecondService?wsdl",
                      endpointInterface = "com.djs.myfirstservice.MyFirstService")
                      
public class MyFirstServiceImpl implements MyFirstService {

    private static final Logger LOG = Logger.getLogger(MyFirstServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.djs.myfirstservice.MyFirstService#newOperation(com.djs.myfirstservice.NewOperation  parameters )*
     */
    public com.djs.myfirstservice.NewOperationResponse newOperation(NewOperation parameters) { 
        LOG.info("Executing operation newOperation");
        System.out.println(parameters);
        try {
            com.djs.myfirstservice.NewOperationResponse _return = new com.djs.myfirstservice.NewOperationResponse();
            _return.setOut("Out-1353331214");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.djs.myfirstservice.MyFirstService#youOperation(com.djs.myfirstservice.YouOperation  parameters )*
     */
    public com.djs.myfirstservice.YouOperationResponse youOperation(YouOperation parameters) throws YouOperationFault_Exception    { 
        LOG.info("Executing operation youOperation");
        System.out.println(parameters);
        try {
            com.djs.myfirstservice.YouOperationResponse _return = new com.djs.myfirstservice.YouOperationResponse();
            _return.setOut("Out-423834296");
            _return.setOut2("Out2-649515458");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new YouOperationFault_Exception("YouOperationFault...");
    }

    /* (non-Javadoc)
     * @see com.djs.myfirstservice.MyFirstService#myOperation(com.djs.myfirstservice.MyOperation  parameters )*
     */
    public com.djs.myfirstservice.MyOperationResponse myOperation(MyOperation parameters) { 
        LOG.info("Executing operation myOperation");
        System.out.println(parameters);
        try {
            com.djs.myfirstservice.MyOperationResponse _return = new com.djs.myfirstservice.MyOperationResponse();
            _return.setOut("Out-1011825822");
            _return.setOut2("Out2-1140980137");
            _return.setNewAttribute("NewAttribute-1447034246");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
