package com.djs.myfirstservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-08-26T23:17:24.548+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://www.example.org/MyServices/", name = "MyFirstService2")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MyFirstService2 {

    @WebResult(name = "NewOperationResponse2", targetNamespace = "http://www.example.org/MyServices/", partName = "parameters")
    @WebMethod(operationName = "NewOperation", action = "http://www.example.org/MyFirstService2/NewOperation")
    public NewOperationResponse2 newOperation(
        @WebParam(partName = "parameters", name = "NewOperation2", targetNamespace = "http://www.example.org/MyServices/")
        NewOperation2 parameters,
        @WebParam(partName = "parameters2", name = "NewOperation2", targetNamespace = "http://www.example.org/MyServices/")
        NewOperation2 parameters2
    );
}
