package com.djs.myfirstservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-08-26T23:17:24.563+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "MySecondService", 
                  wsdlLocation = "http://www.example.org/MySecondService?wsdl",
                  targetNamespace = "http://www.example.org/MyServices/") 
public class MySecondService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/MyServices/", "MySecondService");
    public final static QName MySecondServiceSOAP = new QName("http://www.example.org/MyServices/", "MySecondServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("http://www.example.org/MySecondService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MySecondService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://www.example.org/MySecondService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MySecondService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MySecondService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MySecondService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns MySecondService
     */
    @WebEndpoint(name = "MySecondServiceSOAP")
    public MySecondService getMySecondServiceSOAP() {
        return super.getPort(MySecondServiceSOAP, MySecondService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MySecondService
     */
    @WebEndpoint(name = "MySecondServiceSOAP")
    public MySecondService getMySecondServiceSOAP(WebServiceFeature... features) {
        return super.getPort(MySecondServiceSOAP, MySecondService.class, features);
    }

}
