package com.djs.myfirstservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-08-26T23:17:24.532+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://www.example.org/MyServices/", name = "MySecondService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MySecondService {

    @WebResult(name = "NewOperationResponse", targetNamespace = "http://www.example.org/MyServices/", partName = "parameters")
    @WebMethod(operationName = "NewOperation", action = "http://www.example.org/MySecondService/NewOperation")
    public NewOperationResponse newOperation(
        @WebParam(partName = "parameters", name = "NewOperation", targetNamespace = "http://www.example.org/MyServices/")
        NewOperation parameters
    );
}
