
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.djs.myfirstservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-08-26T23:17:24.485+08:00
 * Generated source version: 2.7.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "MySecondService",
                      portName = "MySecondServiceSOAP",
                      targetNamespace = "http://www.example.org/MyServices/",
                      wsdlLocation = "http://www.example.org/MySecondService?wsdl",
                      endpointInterface = "com.djs.myfirstservice.MySecondService")
                      
public class MySecondServiceImpl implements MySecondService {

    private static final Logger LOG = Logger.getLogger(MySecondServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.djs.myfirstservice.MySecondService#newOperation(com.djs.myfirstservice.NewOperation  parameters )*
     */
    public com.djs.myfirstservice.NewOperationResponse newOperation(NewOperation parameters) { 
        LOG.info("Executing operation newOperation");
        System.out.println(parameters);
        try {
            com.djs.myfirstservice.NewOperationResponse _return = new com.djs.myfirstservice.NewOperationResponse();
            _return.setOut("Out272163715");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
