
package com.djs.myfirstservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-08-26T23:17:24.439+08:00
 * Generated source version: 2.7.6
 */

@WebFault(name = "YouOperationFault", targetNamespace = "http://www.example.org/MyServices/")
public class YouOperationFault_Exception extends Exception {
    
    private com.djs.myfirstservice.YouOperationFault youOperationFault;

    public YouOperationFault_Exception() {
        super();
    }
    
    public YouOperationFault_Exception(String message) {
        super(message);
    }
    
    public YouOperationFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public YouOperationFault_Exception(String message, com.djs.myfirstservice.YouOperationFault youOperationFault) {
        super(message);
        this.youOperationFault = youOperationFault;
    }

    public YouOperationFault_Exception(String message, com.djs.myfirstservice.YouOperationFault youOperationFault, Throwable cause) {
        super(message, cause);
        this.youOperationFault = youOperationFault;
    }

    public com.djs.myfirstservice.YouOperationFault getFaultInfo() {
        return this.youOperationFault;
    }
}
