package com.djs.test.wsclient.session_manager;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.4
 * 2011-11-10T14:19:42.585+08:00
 * Generated source version: 2.4.4
 * 
 */
@WebServiceClient(name = "SessionManagerService", 
                  wsdlLocation = "file:/D:/WorkDJS/Test/JEE_Test/MavenWsSample1/src/main/wsdl/session_manager_service.wsdl",
                  targetNamespace = "http://www.bea.com/wsdl/wlcp/wlng/session_manager/service") 
public class SessionManagerService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.bea.com/wsdl/wlcp/wlng/session_manager/service", "SessionManagerService");
    public final static QName SessionManager = new QName("http://www.bea.com/wsdl/wlcp/wlng/session_manager/service", "SessionManager");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/WorkDJS/Test/JEE_Test/MavenWsSample1/src/main/wsdl/session_manager_service.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SessionManagerService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/WorkDJS/Test/JEE_Test/MavenWsSample1/src/main/wsdl/session_manager_service.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SessionManagerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SessionManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SessionManagerService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SessionManager
     */
    @WebEndpoint(name = "SessionManager")
    public SessionManager getSessionManager() {
        return super.getPort(SessionManager, SessionManager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SessionManager
     */
    @WebEndpoint(name = "SessionManager")
    public SessionManager getSessionManager(WebServiceFeature... features) {
        return super.getPort(SessionManager, SessionManager.class, features);
    }

}
