---
- name: Get local log.
  hosts: VagrantEps
  become: False
  vars:
    local_output_path: ../../Temp
    local_output_file_prefix: Remote_Info_
    local_output_file_postfix: .txt
  tasks:
    - name: Delete old local temp file
      local_action: file path="{{local_output_path}}/{{ local_output_file_prefix }}{{inventory_hostname}}{{local_output_file_postfix}}" state=absent

    - name: Capture output
      command: hostname
      register: result_info

    - name: Save output to local temp file
      # This can append contents to the file.
      local_action: lineinfile line="{{ result_info.stdout }}" dest="{{local_output_path}}/{{ local_output_file_prefix }}{{inventory_hostname}}{{local_output_file_postfix}}" create=Yes


- name: Prepare.
  hosts: 127.0.0.1
  connection: local
  become: False
  vars:
    local_output_file: ../../Temp/Remote_Info.txt
  tasks:
    - name: Delete old local output file
      local_action: file path="{{ local_output_file }}" state=absent
      run_once: True


- name: Combine local log.
  hosts: VagrantEps
  serial: 1
  become: False
  vars:
    local_output_path: ../../Temp
    local_output_file_prefix: Remote_Info_
    local_output_file_postfix: .txt
    local_output_file: ../../Temp/Remote_Info.txt
  tasks:
    - name: Combine temp output to local output file
      # This can append contents to the file.
      local_action: shell cat "{{local_output_path}}/{{ local_output_file_prefix }}{{inventory_hostname}}{{local_output_file_postfix}}" >> "{{ local_output_file }}"

    - name: Delete local temp file
      local_action: file path="{{local_output_path}}/{{ local_output_file_prefix }}{{inventory_hostname}}{{local_output_file_postfix}}" state=absent
