---
- name:  Save remote info to local file
  hosts: VagrantEps
  become: False
  vars:
    local_output_path: ../../Temp
    local_output_file_prefix: Remote_Info_
    local_output_file_postfix: .txt
  tasks:
    - name: Delete old local temp file
      local_action: file path="{{local_output_path}}/{{local_output_file_prefix}}{{inventory_hostname}}{{local_output_file_postfix}}" state=absent

    - name: Capture output
      command: hostname
      register: result_info

    - name: Save output to local temp file
      # Each endpoint has a separated file.
      # This can append contents to the file.
      local_action: lineinfile line="{{result_info.stdout}}" dest="{{local_output_path}}/{{local_output_file_prefix}}{{inventory_hostname}}{{local_output_file_postfix}}" create=Yes


- name: Prepare local file
  hosts: 127.0.0.1
  connection: local
  become: False
  vars:
    local_output_file: ../../Temp/Remote_Info.txt
  tasks:
    - name: Delete old local output file
      local_action: file path="{{local_output_file}}" state=absent
      run_once: True


- name: Combine local temp files into one log file
  hosts: VagrantEps
  # If running concurrently, there will be issue to mutual access the local file.
  serial: 1
  become: False
  vars:
    local_output_path: ../../Temp
    local_output_file_prefix: Remote_Info_
    local_output_file_postfix: .txt
    local_output_file: ../../Temp/Remote_Info.txt
  tasks:
    - name: Combine temp file to one log file
      # This can append contents to the file.
      local_action: shell cat "{{local_output_path}}/{{local_output_file_prefix}}{{inventory_hostname}}{{local_output_file_postfix}}" >> "{{local_output_file}}"

    - name: Delete temp file
      local_action: file path="{{local_output_path}}/{{local_output_file_prefix}}{{inventory_hostname}}{{local_output_file_postfix}}" state=absent
