---
- name: Configure webserver with nginx
  hosts: WebServers
  sudo: True
  tasks:
    - name: install epel repo
      yum:
        name: epel-release
        state: latest
        update_cache: yes

    - name: install nginx
      yum:
        name: nginx
        state: latest
        update_cache: yes

    - name: copy nginx config file
      copy: src=Nginx/nginx.conf dest=/etc/nginx/nginx.conf

    - name: copy index.html
      template: >
        src=Nginx/index.html.j2
        dest=/usr/share/nginx/html/index.html
        mode=0644

    - name: restart nginx
      service: name=nginx state=restarted

