
package com.djs.learn.wsclient.wap_push;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Jan 30 17:41:28 GMT+08:00 2012
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "PolicyException", targetNamespace = "http://www.csapi.org/schema/parlayx/common/v2_1")
public class PolicyException extends Exception {
    public static final long serialVersionUID = 20120130174128L;
    
    private org.csapi.schema.parlayx.common.v2_1.PolicyException policyException;

    public PolicyException() {
        super();
    }
    
    public PolicyException(String message) {
        super(message);
    }
    
    public PolicyException(String message, Throwable cause) {
        super(message, cause);
    }

    public PolicyException(String message, org.csapi.schema.parlayx.common.v2_1.PolicyException policyException) {
        super(message);
        this.policyException = policyException;
    }

    public PolicyException(String message, org.csapi.schema.parlayx.common.v2_1.PolicyException policyException, Throwable cause) {
        super(message, cause);
        this.policyException = policyException;
    }

    public org.csapi.schema.parlayx.common.v2_1.PolicyException getFaultInfo() {
        return this.policyException;
    }
}
