CREATE TABLE URA_CONDOEC_TRANS_HIST (
  PROJECT_NAME                VARCHAR(100) NOT NULL,
  STREET_NAME                 VARCHAR(100) NOT NULL,
  PROPERTY_TYPE               VARCHAR(50) NOT NULL,
  POSTAL_DISTRICT             INT NOT NULL,
  MARKET_SEGMENT              VARCHAR(5) NOT NULL,
  TENURE                      VARCHAR(50) NOT NULL,
  SALE_TYPE                   VARCHAR(20) NOT NULL,
  UNITS                       INT NOT NULL,
  PRICE                       INT NOT NULL,
  FLOOR_AREA                  INT NOT NULL,
  AREA_TYPE                   VARCHAR(20) NOT NULL,
  FLOOR_LEVEL                 VARCHAR(20) NOT NULL,
  PRICE_PSM                   INT NOT NULL,
  SALE_DATE                   VARCHAR(20) NOT NULL,
  TENURE_YEAR                 INT NOT NULL,
  TENURE_LENGTH               INT NOT NULL,
  FLOOR_AREA_LOWER            INT NOT NULL,
  FLOOR_AREA_UPPER            INT NOT NULL,
  SALE_YEAR                   INT NOT NULL
);

CREATE INDEX URA_CONDOEC_TRANS_HIST_1 ON URA_CONDOEC_TRANS_HIST (POSTAL_DISTRICT, SALE_YEAR, FLOOR_AREA_LOWER, PRICE);

CREATE TABLE URA_CONDOEC_RENT_HIST (
  PROJECT_NAME                VARCHAR(100) NOT NULL,
  STREET_NAME                 VARCHAR(100) NOT NULL,
  POSTAL_DISTRICT             INT NOT NULL,
  PROPERTY_TYPE               VARCHAR(50) NOT NULL,
  BEDROOM_NUM                 INT NOT NULL,
  MONTHLY_GROSS_RENT          INT NOT NULL,
  FLOOR_AREA                  VARCHAR(20) NOT NULL,
  LEASE_DATE                  VARCHAR(20) NOT NULL,
  YEARLY_GROSS_RENT           INT NOT NULL,
  FLOOR_AREA_LOWER            INT NOT NULL,
  FLOOR_AREA_UPPER            INT NOT NULL,
  LEASE_YEAR                  INT NOT NULL
);

CREATE INDEX URA_CONDOEC_RENT_HIST_1 ON URA_CONDOEC_RENT_HIST (POSTAL_DISTRICT, LEASE_YEAR, FLOOR_AREA_LOWER, YEARLY_GROSS_RENT);
