
package com.djs.test.wsclient.session_manager;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Jan 30 17:41:27 GMT+08:00 2012
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "fault", targetNamespace = "http://www.bea.com/wsdl/wlcp/wlng/session_manager/service")
public class GeneralException extends Exception {
    public static final long serialVersionUID = 20120130174127L;
    
    private com.djs.test.wsclient.session_manager.Fault fault;

    public GeneralException() {
        super();
    }
    
    public GeneralException(String message) {
        super(message);
    }
    
    public GeneralException(String message, Throwable cause) {
        super(message, cause);
    }

    public GeneralException(String message, com.djs.test.wsclient.session_manager.Fault fault) {
        super(message);
        this.fault = fault;
    }

    public GeneralException(String message, com.djs.test.wsclient.session_manager.Fault fault, Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public com.djs.test.wsclient.session_manager.Fault getFaultInfo() {
        return this.fault;
    }
}
