
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.djs.ws.myfirstservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.12
 * Thu Aug 22 10:43:31 SGT 2013
 * Generated source version: 2.2.12
 * 
 */

@javax.jws.WebService(
                      serviceName = "MyFirstService",
                      portName = "MyFirstServiceSOAP",
                      targetNamespace = "http://www.example.org/MyFirstService/",
                      wsdlLocation = "http://www.example.org/?wsdl",
                      endpointInterface = "com.djs.ws.myfirstservice.MyFirstService")
                      
public class MyFirstServiceImpl implements MyFirstService {

    private static final Logger LOG = Logger.getLogger(MyFirstServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.djs.ws.myfirstservice.MyFirstService#newOperation(java.lang.String  in )*
     */
    public java.lang.String newOperation(java.lang.String in) { 
        LOG.info("Executing operation newOperation");
        System.out.println(in);
        try {
            java.lang.String _return = "_return104439243";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
