
/*
 * 
 */

package com.djs.learn.ws.myfirstservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.12
 * Thu Aug 22 10:43:31 SGT 2013
 * Generated source version: 2.2.12
 * 
 */


@WebServiceClient(name = "MyFirstService", 
                  wsdlLocation = "http://www.example.org/?wsdl",
                  targetNamespace = "http://www.example.org/MyFirstService/") 
public class MyFirstService_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.example.org/MyFirstService/", "MyFirstService");
    public final static QName MyFirstServiceSOAP = new QName("http://www.example.org/MyFirstService/", "MyFirstServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("http://www.example.org/?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://www.example.org/?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public MyFirstService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MyFirstService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyFirstService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns MyFirstService
     */
    @WebEndpoint(name = "MyFirstServiceSOAP")
    public MyFirstService getMyFirstServiceSOAP() {
        return super.getPort(MyFirstServiceSOAP, MyFirstService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyFirstService
     */
    @WebEndpoint(name = "MyFirstServiceSOAP")
    public MyFirstService getMyFirstServiceSOAP(WebServiceFeature... features) {
        return super.getPort(MyFirstServiceSOAP, MyFirstService.class, features);
    }

}
