VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use the same SSH key for each VM.
  config.ssh.insert_key = false
  config.vm.box = "Sliim/kali-2018.1-amd64"

  # This message will run when all other completed.
  config.vm.post_up_message = "Test environment for Kali Linux."

  # Use DHCP gateway.
  config.vm.network "public_network", use_dhcp_assigned_default_route: true
  # Not use DHCP IP, will configure IP manually.
  config.vm.network "public_network", auto_config: false

  config.vm.define "kaliLinux" do |kaliLinux|
    kaliLinux.vm.provider "virtualbox" do |vb|
      vb.name = "Vagrant_KaliLinux"
      # Default is 1024M.
      vb.memory = 3072
      # Default is 1 CPU.
      vb.cpus = 2
      vb.gui = true
    end
  end
end
