VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use the same SSH key for each VM.
  config.ssh.insert_key = false
  config.vm.box = "Sliim/kali-2018.1-amd64"

  # This message will run when all other completed.
  config.vm.post_up_message = "Test environment for Kali Linux."

  # Adapter 2: Use private network Host-Only with fixed IP in same subnet.
  # Netmask 192.168.10.0/24
  # Host can access them.
  # They can access each other, host and Internet.

  config.vm.define "kaliLinux" do |kaliLinux|
    kaliLinux.vm.provider "virtualbox" do |vb|
      vb.name = "Vagrant_KaliLinux"
      # Default is 1024M.
      vb.memory = 3072
      # Default is 1 CPU.
      vb.cpus = 2
      vb.gui = true
    end
    kaliLinux.vm.network "private_network", ip: "192.168.10.81"
  end
end
