//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.08 at 05:01:36 PM GMT+08:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bea.com/wsdl/wlcp/wlng/session_manager/service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.djs.test.wsclient.session_manager;
