# For some installation, may need to set this default values.
# This file can use ENV variables directly.
path:
  home: /usr/share/filebeat
  config: /etc/filebeat
  data: /data/filebeat
  logs: /var/log/filebeat

output:
  logstash:
    enabled: true
    hosts:
      - "${LOGSTASH_URL}"
    timeout: 15

filebeat:
  prospectors:
    - input_type: log
      paths:
        - /host/log/dmesg
        - /host/log/secure
    - input_type: log
      paths:
        - /host/log/messages
