
package com.bea.wsdl.wlcp.wlng.session_manager.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SessionManagerService", targetNamespace = "http://www.bea.com/wsdl/wlcp/wlng/session_manager/service", wsdlLocation = "file:/D:/WorkDJS/Test/JEE_Test/MavenSample2/src/main/wsdl/session_manager_service.wsdl")
public class SessionManagerService
    extends Service
{

    private final static URL SESSIONMANAGERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.bea.wsdl.wlcp.wlng.session_manager.service.SessionManagerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.bea.wsdl.wlcp.wlng.session_manager.service.SessionManagerService.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/WorkDJS/Test/JEE_Test/MavenSample2/src/main/wsdl/session_manager_service.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/WorkDJS/Test/JEE_Test/MavenSample2/src/main/wsdl/session_manager_service.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SESSIONMANAGERSERVICE_WSDL_LOCATION = url;
    }

    public SessionManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SessionManagerService() {
        super(SESSIONMANAGERSERVICE_WSDL_LOCATION, new QName("http://www.bea.com/wsdl/wlcp/wlng/session_manager/service", "SessionManagerService"));
    }

    /**
     * 
     * @return
     *     returns SessionManager
     */
    @WebEndpoint(name = "SessionManager")
    public SessionManager getSessionManager() {
        return super.getPort(new QName("http://www.bea.com/wsdl/wlcp/wlng/session_manager/service", "SessionManager"), SessionManager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SessionManager
     */
    @WebEndpoint(name = "SessionManager")
    public SessionManager getSessionManager(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.bea.com/wsdl/wlcp/wlng/session_manager/service", "SessionManager"), SessionManager.class, features);
    }

}
