VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use the same SSH key for each VM.
  config.ssh.insert_key = false
  config.vm.box = "bento/centos-7.3"

  # This message will run when all other completed.
  config.vm.post_up_message = "Test environment for Ansible servers."

  # Use DHCP gateway.
  config.vm.network "public_network", use_dhcp_assigned_default_route: true
  # Not use DHCP IP, will configure IP manually.
  config.vm.network "public_network", auto_config: false

  # This is default folder mapping.
  config.vm.synced_folder "F:/Download/Shared", "/vagrant", owner: "root", group: "root"

  config.vm.define "ansibleDbServer" do |ansibleDbServer|
    ansibleDbServer.vm.provider "virtualbox" do |vb|
      vb.name = "Vagrant_AnsibleDbServer"
      # Default is 1024M.
      vb.memory = 2048
      # Default is 1 CPU.
      vb.cpus = 2
    end

    ansibleDbServer.vm.hostname = "db.djsilenceboy.com"

    # Local provision will run after global provision.
    # Configure IP manually.
    ansibleDbServer.vm.provision "shell", run: "always", inline: "ifconfig enp0s8 192.168.0.42 netmask 255.255.255.0 up"
  end

  config.vm.define "ansibleApplicationServer" do |ansibleApplicationServer|
    ansibleApplicationServer.vm.provider "virtualbox" do |vb|
      vb.name = "Vagrant_AnsibleApplicationServer"
      # Default is 1024M.
      vb.memory = 3072
      # Default is 1 CPU.
      vb.cpus = 2
    end

    ansibleApplicationServer.vm.hostname = "appsvr.djsilenceboy.com"

    # Local provision will run after global provision.
    # Configure IP manually.
    ansibleApplicationServer.vm.provision "shell", run: "always", inline: "ifconfig enp0s8 192.168.0.43 netmask 255.255.255.0 up"
  end

  config.vm.define "ansibleJbossServer" do |ansibleJbossServer|
    ansibleJbossServer.vm.provider "virtualbox" do |vb|
      vb.name = "Vagrant_AnsibleJbossServer"
      # Default is 1024M.
      vb.memory = 3072
      # Default is 1 CPU.
      vb.cpus = 2
    end

    ansibleJbossServer.vm.hostname = "jboss.djsilenceboy.com"

    # Local provision will run after global provision.
    # Configure IP manually.
    ansibleJbossServer.vm.provision "shell", run: "always", inline: "ifconfig enp0s8 192.168.0.44 netmask 255.255.255.0 up"
  end

  config.vm.define "ansibleDockerServer" do |ansibleDockerServer|
    ansibleDockerServer.vm.provider "virtualbox" do |vb|
      vb.name = "Vagrant_AnsibleDockerServer"
      # Default is 1024M.
      vb.memory = 3072
      # Default is 1 CPU.
      vb.cpus = 2
    end

    ansibleDockerServer.vm.hostname = "docker.djsilenceboy.com"

    # Local provision will run after global provision.
    # Configure IP manually.
    ansibleDockerServer.vm.provision "shell", run: "always", inline: "ifconfig enp0s8 192.168.0.45 netmask 255.255.255.0 up"
  end
end
