
package org.csapi.wsdl.parlayx.djs.sample.ext.wappush.v1_0.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WapPushService", targetNamespace = "http://www.csapi.org/wsdl/parlayx/djs/sample/ext/wappush/v1_0/service", wsdlLocation = "file:/D:/WorkDJS/Test/JEE_Test/MavenSample2/src/main/wsdl/some_parlayx_wappush_service_1_0.wsdl")
public class WapPushService
    extends Service
{

    private final static URL WAPPUSHSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.csapi.wsdl.parlayx.djs.sample.ext.wappush.v1_0.service.WapPushService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.csapi.wsdl.parlayx.djs.sample.ext.wappush.v1_0.service.WapPushService.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/WorkDJS/Test/JEE_Test/MavenSample2/src/main/wsdl/some_parlayx_wappush_service_1_0.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/WorkDJS/Test/JEE_Test/MavenSample2/src/main/wsdl/some_parlayx_wappush_service_1_0.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WAPPUSHSERVICE_WSDL_LOCATION = url;
    }

    public WapPushService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WapPushService() {
        super(WAPPUSHSERVICE_WSDL_LOCATION, new QName("http://www.csapi.org/wsdl/parlayx/djs/sample/ext/wappush/v1_0/service", "WapPushService"));
    }

    /**
     * 
     * @return
     *     returns ExtWapPush
     */
    @WebEndpoint(name = "ExtWapPush")
    public ExtWapPush getExtWapPush() {
        return super.getPort(new QName("http://www.csapi.org/wsdl/parlayx/djs/sample/ext/wappush/v1_0/service", "ExtWapPush"), ExtWapPush.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExtWapPush
     */
    @WebEndpoint(name = "ExtWapPush")
    public ExtWapPush getExtWapPush(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.csapi.org/wsdl/parlayx/djs/sample/ext/wappush/v1_0/service", "ExtWapPush"), ExtWapPush.class, features);
    }

}
