VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use the same SSH key for each VM.
  config.ssh.insert_key = false
  config.vm.box = "centos/7"

  # This message will run when all other completed.
  config.vm.post_up_message = "Test environment for Ansible servers."

  # Adapter 2: Use private network Host-Only with fixed IP in same subnet.
  # Netmask 192.168.10.0/24
  # Host can access them.
  # They can access each other, host and Internet.

  # This is default folder mapping.
  # config.vm.synced_folder "./Temp", "/vagrant", owner: "root", group: "root"

  # Global config.
  # Enable password login.
  config.vm.provision "shell", inline: <<-END
    # Testing: sudo sed "/^PasswordAuthentication.*$/d; /^#PasswordAuthentication.*$/a PasswordAuthentication yes" /etc/ssh/sshd_config
    sudo sed -i "/^PasswordAuthentication.*$/d" /etc/ssh/sshd_config
    sudo sed -i "/^#PasswordAuthentication.*$/a PasswordAuthentication yes" /etc/ssh/sshd_config
    sudo systemctl restart sshd
  END


  config.vm.define "ansibleDockerServer2" do |ansibleDockerServer2|
    ansibleDockerServer2.vm.provider "virtualbox" do |vb|
      vb.name = "Vagrant_ansibleDockerServer2"
      # Default is 1024M.
      vb.memory = 2048
      # Default is 1 CPU.
      vb.cpus = 2
    end

    ansibleDockerServer2.vm.hostname = "docker2.djsilenceboy.com"
    ansibleDockerServer2.vm.network "private_network", ip: "192.168.10.17"
  end
end
