CREATE TABLE TEST_ITEM
(
  SEQ_ID                     NUMBER,
  ITEM_NAME                  VARCHAR2(100 BYTE),
  DESCRIPTION                VARCHAR2(1000 BYTE),
  ADD_TIME                   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_TEST_ITEM PRIMARY KEY (SEQ_ID)
);
