---
- name: Install development tools
  hosts: VagrantApplicationServer
  sudo: True
  tasks:
    - name: Install development group
      yum:
        name: "@Development Tools"
        state: present
        update_cache: yes

    - name: Install tools
      yum:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - python-devel
        - openssl-devel


- name: Install Ansible
  hosts: VagrantApplicationServer
  sudo: True
  tasks:
    - name: Install application
      shell: pip install ansible


- name: Install httpd
  hosts: VagrantApplicationServer
  sudo: True
  tasks:
    - name: Install application
      yum:
        name: httpd
        state: latest
        update_cache: yes

    - name: Config service
      shell: sed -i "s/\(ServerName\).*$/\1  "$(hostname)"/g" /etc/httpd/conf/httpd.conf

    - name: Enable and start service
      service:
        name: httpd
        enabled: yes
        state: started


- name: Install Tomcat v8.0
  hosts: VagrantApplicationServer
  sudo: True
  vars:
    local_installation_file_path: /cygdrive/f/Download/Shared
    local_config_file_path: files
    remote_temp_path: /tmp
    tomcat_installation_file: apache-tomcat-8.0.39.zip
    tomcat_installation_parentfolder: /opt
    tomcat_installation_tempfolder: apache-tomcat-8.0.39
    tomcat_installation_folder: tomcat
    service_file: tomcat.service
  tasks:
    - name: Add Linux group
      group:
        name: tomcat
        state: present

    - name: Add Linux user
      user:
        name: tomcat
        shell: /bin/nologin
        createhome: no
        home: "{{ tomcat_installation_parentfolder }}/{{ tomcat_installation_folder }}"
        group: tomcat
        groups: root
        append: yes
        state: present

    - name: Copy installation file to remote
      copy:
        src: "{{ local_installation_file_path }}/{{ tomcat_installation_file }}"
        dest: "{{ remote_temp_path }}"

    - name: Unzip installation file
      unarchive:
        src: "{{ remote_temp_path }}/{{ tomcat_installation_file }}"
        dest: "{{ tomcat_installation_parentfolder }}"
        remote_src: True

    - name: Rename installation folder
      shell: chdir="{{ tomcat_installation_parentfolder }}" mv "{{ tomcat_installation_tempfolder }}" "{{ tomcat_installation_folder }}"

    - name: Copy plugin/addon files to remote
      copy:
        src: "{{ local_installation_file_path }}/{{ item }}"
        dest: "{{ tomcat_installation_parentfolder }}/{{ tomcat_installation_folder }}/lib"
      with_items:
        - catalina-jmx-remote.jar
        - catalina-ws.jar

    - name: Change installation folder privilege
      file:
        state: directory
        path: "{{ tomcat_installation_parentfolder }}/{{ tomcat_installation_folder }}"
        group: tomcat
        owner: tomcat
        mode: u+rwx,g+rwx,o+rx
        recurse: yes

    - name: Some useful links
      file:
        state: link
        path: "{{ item.dest }}"
        src: "{{ item.src }}"
      with_items:
        - {src: "{{ tomcat_installation_parentfolder }}/{{ tomcat_installation_folder }}/conf", dest: "/etc/tomcat"}
        - {src: "{{ tomcat_installation_parentfolder }}/{{ tomcat_installation_folder }}/logs", dest: "/var/log/tomcat"}

    - name: Add admin user
      shell: sed -i '/<\/tomcat-users>/ i\  <user name="admin" password="P@ssw0rd" roles="admin-gui,manager-gui"/>' /etc/tomcat/tomcat-users.xml

    - name: Copy service file to remote
      copy:
        src: "{{ local_config_file_path }}/{{ service_file }}"
        dest: /etc/systemd/system

    - name: Reload service
      systemd:
        name: tomcat
        state: reloaded

    - name: Enable and start service
      service:
        name: tomcat
        enabled: yes
        state: started


- name: Install Jenkins
  hosts: VagrantApplicationServer
  sudo: True
  vars:
    local_installation_file_path: /cygdrive/f/Download/Shared
    jenkins_installation_file: jenkins.war
    tomcat_folder: /opt/tomcat/webapps
    jenkins_folder: /opt/jenkins
  tasks:
    - name: Create working folder
      file:
        state: directory
        path: "{{ jenkins_folder }}"
        group: tomcat
        owner: tomcat
        mode: u+rwx,g+rwx,o+rw
        recurse: yes

    - name: Add config in Tomcat service
      shell: sed -i '/.*JAVA_OPTS.*/ a\Environment=JENKINS_HOME=/opt/jenkins' /etc/systemd/system/tomcat.service

    - name: Copy installation file to remote
      copy:
        src: "{{ local_installation_file_path }}/{{ jenkins_installation_file }}"
        dest: "{{ tomcat_folder }}"

    - name: Change privileges
      file:
        state: file
        path: "{{ tomcat_folder }}/{{ jenkins_installation_file }}"
        group: tomcat
        owner: tomcat
        mode: u+rwx,g+rwx,o+rw

    - name: Reload and restart service
      service:
        name: tomcat
        daemon_reload: true
        state: restarted
