---
- name: Install JBoss EAP v7.0
  hosts: VagrantJbossServer
  become: True
  vars:
    local_installation_file_path: /cygdrive/f/Download/Shared
    local_config_file_path: files
    remote_temp_path: /tmp
    jboss_installation_file: jboss-eap-7.0.0-installer.jar
    local_jdbc_file_path: /cygdrive/f/Download/Shared/JDBC_Drivers
    jboss_config_file: JBoss_AddJDBCDrivers.sh
  tasks:
    - name: Copy installation file to remote
      copy:
        src: "{{ local_installation_file_path }}/{{ jboss_installation_file }}"
        dest: "{{ remote_temp_path }}"

    - name: Copy installation config files to remote
      copy:
        src: "{{ item }}"
        dest: "{{ remote_temp_path }}/"
      with_fileglob:
        - "{{ local_config_file_path }}/auto.xml*"

    - name: Install application
      shell: chdir="{{ remote_temp_path }}" java -jar jboss-eap-7.0.0-installer.jar auto.xml

    - name: Config as a Service 1
      shell: cp /opt/eap7/bin/init.d/jboss-eap.conf /etc/default

    - name: Config as a Service 2
      shell: cp /opt/eap7/bin/init.d/jboss-eap-rhel.sh /etc/init.d

    - name: Config as a Service 3
      shell: chmod +x /etc/init.d/jboss-eap-rhel.sh

    - name: Config service 1
      shell: sed -i "s/^.*JBOSS_HOME.*$/JBOSS_HOME=\"\/opt\/eap7\"/g" /etc/default/jboss-eap.conf

    - name: Config service 2
      shell: sed -i "s/^.*JBOSS_USER.*$/JBOSS_USER=root/g" /etc/default/jboss-eap.conf

    - name: Enable remote access
      shell: sed -i "$ a\JBOSS_OPTS=\"\$JBOSS_OPTS -Djboss.bind.address.management=0.0.0.0 -Djboss.bind.address=0.0.0.0\"" /etc/default/jboss-eap.conf

    - name: Enable service 1
      shell: chkconfig --add jboss-eap-rhel.sh

    - name: Enable service 2
      shell: chkconfig jboss-eap-rhel.sh on

    - name: Start service
      service:
        name: jboss-eap-rhel
        state: started

    - name: Sleep
      pause:
        seconds: 5

    - name: Copy JDBC driver files to remote
      copy:
        src: "{{ item }}"
        dest: "{{ remote_temp_path }}/"
      with_fileglob:
        - "{{ local_jdbc_file_path }}/*"

    - name: Copy config file to remote
      copy:
        src: "{{ local_config_file_path }}/{{ jboss_config_file }}"
        dest: "{{ remote_temp_path }}"
        mode: "a+x"

    - name: Add JDBC
      shell: "{{ remote_temp_path }}/{{ jboss_config_file }}"
