package com.djs.learn.wsclient.example_test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Jan 30 17:41:27 GMT+08:00 2012
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://djs.com/some/example_test/v1_0/interface", name = "SendDataPort")
@XmlSeeAlso({org.csapi.schema.parlayx.common.v2_1.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SendDataPort {

    @WebResult(name = "sendDataResponse", targetNamespace = "http://djs.com/schema/example_test/local", partName = "result")
    @WebMethod
    public SendDataResponse sendData(
        @WebParam(partName = "parameters", name = "sendDataRequest", targetNamespace = "http://djs.com/schema/example_test/local")
        SendDataRequest parameters
    ) throws ServiceException, PolicyException;
}
