
/*
 * 
 */

package com.djs.learn.wsclient.example_test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Jan 30 17:41:27 GMT+08:00 2012
 * Generated source version: 2.2.9
 * 
 */


@WebServiceClient(name = "SendDataService", 
                  wsdlLocation = "file:/D:/WorkDJS/Test/JEE_Test/MavenWsSample1/src/main/wsdl/some_example_test_service.wsdl",
                  targetNamespace = "http://djs.com/some/example_test/v1_0/service") 
public class SendDataService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://djs.com/some/example_test/v1_0/service", "SendDataService");
    public final static QName SendDataPort = new QName("http://djs.com/some/example_test/v1_0/service", "SendDataPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/WorkDJS/Test/JEE_Test/MavenWsSample1/src/main/wsdl/some_example_test_service.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/D:/WorkDJS/Test/JEE_Test/MavenWsSample1/src/main/wsdl/some_example_test_service.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SendDataService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SendDataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendDataService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns SendDataPort
     */
    @WebEndpoint(name = "SendDataPort")
    public SendDataPort getSendDataPort() {
        return super.getPort(SendDataPort, SendDataPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendDataPort
     */
    @WebEndpoint(name = "SendDataPort")
    public SendDataPort getSendDataPort(WebServiceFeature... features) {
        return super.getPort(SendDataPort, SendDataPort.class, features);
    }

}
