package com.djs.learn.wsclient.wap_push;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.4
 * 2011-11-10T11:36:23.314+08:00
 * Generated source version: 2.4.4
 * 
 */
@WebService(targetNamespace = "http://www.csapi.org/wsdl/parlayx/djs/sample/ext/wappush/v1_0/interface", name = "ExtWapPush")
@XmlSeeAlso({org.csapi.schema.parlayx.common.v2_1.ObjectFactory.class, ObjectFactory.class})
public interface ExtWapPush {

    @WebResult(name = "wapPushResponse", targetNamespace = "http://www.csapi.org/schema/parlayx/djs/sample/ext/wappush/v1_0/local")
    @RequestWrapper(localName = "sendWapPush", targetNamespace = "http://www.csapi.org/schema/parlayx/djs/sample/ext/wappush/v1_0/local", className = "com.djs.learn.wsclient.wap_push.SendWapPush")
    @WebMethod
    @ResponseWrapper(localName = "sendWapPushResponse", targetNamespace = "http://www.csapi.org/schema/parlayx/djs/sample/ext/wappush/v1_0/local", className = "com.djs.learn.wsclient.wap_push.SendWapPushResponse")
    public com.djs.learn.wsclient.wap_push.WapPushRespData sendWapPush(
        @WebParam(name = "wapPushRequest", targetNamespace = "http://www.csapi.org/schema/parlayx/djs/sample/ext/wappush/v1_0/local")
        com.djs.learn.wsclient.wap_push.WapPushReqData wapPushRequest
    ) throws PolicyException, ServiceException;
}
